SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN '08' AND '10'
    GROUP BY CAR_ID
    HAVING MONTH(START_DATE) BETWEEN '08' AND '10' AND COUNT(CAR_ID) >= 5)
GROUP BY CAR_ID,MONTH
HAVING RECORDS >= 1
ORDER BY MONTH, CAR_ID DESC;
