WITH MonthlySales AS (
    SELECT
        B.AUTHOR_ID,
        A.AUTHOR_NAME,
        B.CATEGORY,
        SUM(B.PRICE * S.SALES) AS TOTAL_SALES
    FROM
        BOOK B
        JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
        JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
    WHERE
        EXTRACT(YEAR FROM S.SALES_DATE) = 2022
        AND EXTRACT(MONTH FROM S.SALES_DATE) = 1
    GROUP BY
        B.AUTHOR_ID,
        A.AUTHOR_NAME,
        B.CATEGORY
)
SELECT
    AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    TOTAL_SALES
FROM
    MonthlySales
ORDER BY
    AUTHOR_ID ASC,
    CATEGORY DESC;
