SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d')
from MEMBER_PROFILE
where DATE_FORMAT(DATE_OF_BIRTH, "%m") = '03'
and GENDER = 'W'
and TLNO is NOT NULL
order by MEMBER_ID;