SELECT S1.ITEM_ID, S1.ITEM_NAME, S1.RARITY
FROM ITEM_INFO I2,
(
SELECT I1.ITEM_ID, T1.PARENT_ITEM_ID, I1.ITEM_NAME, I1.RARITY
FROM ITEM_TREE T1, ITEM_INFO I1
WHERE T1.ITEM_ID = I1.ITEM_ID
) S1
WHERE S1.PARENT_ITEM_ID = I2.ITEM_ID
AND I2.RARITY = "RARE"
ORDER BY S1.ITEM_ID DESC
